import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarDemo from "@/components/Navbar";
import { SparklesPreview } from "@/components/SparklesPreview";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mohit's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/globe.svg", // Path inside public/
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <SparklesPreview />
        <div className="relative w-full flex items-center justify-center">
          <NavbarDemo />
        </div>
        {children}
      </body>
    </html>
  );
}
